server {
    
    listen 80;
    resolver 127.0.0.11 valid=30s;

    return 301 https://$host$request_uri;
}

server {

    listen 443 ssl;
    resolver 127.0.0.11 valid=30s;


    ssl_certificate /etc/ssl/certs/event.crt;
    ssl_certificate_key /etc/ssl/private/event.key;
    

    set $frontend http://frontend:80;
    set $events http://event-service:5001;
    set $registrations http://registration-service:5002;

    location / {
        proxy_pass $frontend;
    }

    location /api/events/ {
        rewrite ^/api/events/(.*) /$1 break;
        proxy_pass $events;
    }

    location /api/registrations/ {
        rewrite ^/api/registrations/(.*) /$1 break;
        proxy_pass $registrations/;

    }
}