server {
    listen 80;

    # де шукати файли для роздачі
    root /usr/share/nginx/html;

    # який файл відкривати за замовчуванням
    index index.html;

    # для будь-якого запиту — роздавати файли
    location / {
        try_files $uri $uri/ /index.html;
    }
}
